### ISSUE TITLE
IPython 3 updates

### ISSUE THREAD

**Issue by stared** [ipython-books/minibook-code#1]
In IPython world 2 years is a lot of time (`0.x` -> `3.0`). Do you plan re-releasing a newer version of IPython Minibook? (As I do enjoy reading IPython Cookbook, I am looking for some introduction/reference for teaching (I)Python to scientists.)

**Comment by rossant** [comment]
Absolutely! I'm currently finalizing the first draft of the second edition which should be released this spring. The second edition will target IPython 3.0. It will also feature a short beginner-friendly introduction to the Python language, and it will cover pandas in more details.

**Comment by stared** [comment]
I am looking forward to it! Any pre-opening night release? :)

**Comment by rossant** [comment]
There's a new edition now!
